---

port: 4000
host: 0.0.0.0
safe: false

url: https://chiuro.github.io
baseurl: /agency-jekyll

# Site settings
title: RES s.c.s.
email: your-email@domain.com
description: "Ricerca Educativa Servizio"


# Team names, titles and social links
people:
- name: Cleo
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: R2-D2
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: C3-PO
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: via delle ginestre, 1
  - line: CIRIE' (TO) 10073

# Build settings
markdown: kramdown
permalink: pretty