---

#port: 4000
#host: 0.0.0.0
#safe: false

#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: RES
email: your-email@domain.com
description: "Ricerca Educativa Servizio"


# Team names, titles and social links
people:
- name: Vale
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: test
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: via delle ginestre, 1
  - line: CIRIE' (TO) 10073

# Build settings
markdown: kramdown
permalink: pretty